### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by SpiderMath** [SpiderMath/Contrast#1]
- [x] Think of a way to read JSON Files, without them compiling, and ruining other stuff
- [ ] Add Auto Command DocGen
- [ ] Add Image Manipulation commands
- [ ] Add Economy
- [ ] Lol Counter
- [ ] OwO Counter
- [ ] Lichess Puzzle, solver and stuff :man_shrugging:
